### ISSUE TITLE
campaign condition is wrongly updated

### ISSUE THREAD

**Issue by ebenjoee** [nokibsarkar/bot-wikifolklore-issues#11] opened 2024-02-06 17:35 UTC
the condition for the ongoing feminism campaign is that either 4000 bytes OR 400 words but, in this tool, it checks for both the condition to fulfill.
it accepts the articles which meets both the conditions. 

**Instead of OR it takes AND**

**Comment by Tiven2240** [comment] 2024-02-06 17:49
Thank you @ebenjoee to bring this on our notice. The technical team has taken this on utmost priority and will be fixed soon. We wish you all the best for the campaign.

@nokibsarkar please take this forward.

**Comment by nokibsarkar** [comment] 2024-02-06 18:13
@Tiven2240 @ebenjoee Thank you very much. After discussing with my team, we decided to allow `OR` instead of <s>`AND`</s>. Therefore, if the restrictions are 4000 bytes 400 words, they are to be implemented as 4000 bytes `OR` 400 words. This is global fix as of now. So, it would be applied on all the campaigns. The issue is officially fixed. Thank you very much. We would appreciate any type of feedback (via our feedback system) or contribution (via bug reports or [translation of the interface](https://tools.wikilovesfolklore.org/campwiz/translate)).

**Closed as completed by nokibsarkar** 2024-02-06 18:13 UTC
